version: '3.8'

services:
  bot:
    build: .
    container_name: chess_courses_bot
    restart: always
    volumes:
      - ./.env:/app/.env
    environment:
      - TZ=UTC
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - chess_network

  redis:
    image: redis:7-alpine
    container_name: chess_redis
    restart: always
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    networks:
      - chess_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  chess_network:
    driver: bridge